server:
  port: 8080

spring:
  application:
    name: webtest
  redis:
    host: 47.95.222.174
    port: 6379
    password: 123456
    database: 0
    lettuce:
      pool:
        min-idle: 1
        max-active: 5


